### PR TITLE
bug/35 Fixed crawling of multimodule projects

### LINKED ISSUE #35: Maven-plugin can't trace projects with multiple maven modules
Currently, the maven plugin can't trace projects that contain multiple maven submodules.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #35

### CODE REVIEW

File: src/main/java/org/itsallcode/openfasttrace/maven/TraceMojo.java [hunk 1]
```diff
@@ -199,11 +198,39 @@ private ImportSettings createImportSettings()
 
     private List<Path> getSourcePaths()
     {
-        return Stream
+        return getSourcePathOfProject(this.project);
+    }
+
+    private Path getPomOfSubModule(String moduleName)
+    {
+        return this.project.getBasedir().toPath().resolve(moduleName).resolve("pom.xml");
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/openfasttrace/maven/TraceMojo.java:206]: Will this work with nested projects, e.g. when the module is located in `<basedir>/plugins/moduleA`?

**Review by kaklakariada — CHANGES_REQUESTED** [review]
Looks good!
Please add a changelog entry

File: src/main/java/org/itsallcode/openfasttrace/maven/TraceMojo.java (hunk 1 above)
Comment (kaklakariada) [reply src/main/java/org/itsallcode/openfasttrace/maven/TraceMojo.java:206]: Added an integration test, works ✔️

File: pom.xml [hunk 2]
```diff
@@ -5,7 +5,7 @@
 
     <groupId>org.itsallcode</groupId>
     <artifactId>openfasttrace-maven-plugin</artifactId>
-    <version>1.2.1</version>
+    <version>1.3.0</version>
```
Comment (kaklakariada) [inline pom.xml:8]: @jakobbraun integration tests are failing after updating the version number. Do you have any idea why this happens?

**Review by kaklakariada — CHANGES_REQUESTED** [review]
